// modesta - Lightweight swagger proxy generator
// Copyright (c) Kouji Matsui (@kekyo@mi.kekyo.net)
// Under MIT.
// https://github.com/kekyo/modesta/

import { JsonRecord } from '../types';
import {
  AccessorGroupDefinition,
  ApiDefinition,
  OpenApiContext,
  OperationDefinition,
  ParameterDefinition,
  ResponseDefinition,
  SchemaDefinition,
} from './types';
import { resolveReferenceObject, resolveSchemaObject } from './resolve';
import {
  asArray,
  asRecord,
  fail,
  getBoolean,
  getDirectReference,
  getRecord,
  getRequiredRecord,
  getRequiredString,
  getSingleReferenceFromAllOf,
  getString,
  indent,
  isAllOfReferenceWrapperSchema,
  isPureReference,
  isReferenceWrapperSchema,
  renderLiteral,
  renderPropertyName,
} from '../util';
import { version } from '../generated/packageMetadata';
import { basename } from 'path';
import { fileURLToPath } from 'url';

//////////////////////////////////////////////////////////////////////////

const anonymizeSourceFileDisplay = (source: string) => {
  try {
    const url = new URL(source);
    if (url.protocol === 'file:') {
      return basename(fileURLToPath(url));
    }
    if (url.protocol !== 'http:' && url.protocol !== 'https:') {
      return source;
    }

    url.hostname = 'example.com';
    url.port = '';
    url.username = '';
    url.password = '';
    return url.href;
  } catch {
    return basename(source);
  }
};

export const renderApiDefinition = (
  api: ApiDefinition,
  context: OpenApiContext
) => {
  const lines: string[] = [];
  const push = (value = '') => {
    lines.push(value);
  };

  push('// @ts-nocheck');
  push(`// This file is auto-generated by modesta [${version}]`);
  push('// Do not edit manually');

  if (api.title != null) {
    push(`// Source title: ${api.title}`);
  }
  if (api.source != null) {
    push(`// Source file: ${anonymizeSourceFileDisplay(api.source)}`);
  }
  push();
  push(
    '/////////////////////////////////////////////////////////////////////////////////'
  );
  push();

  push(
    renderInterfaceDefinition(
      'AccessorRequestDescriptor<TRequestBody>',
      'Prepared request descriptor used by generated accessors.',
      [
        renderInterfaceMember(
          'operationName',
          'string',
          false,
          'Stable operation name used for diagnostics and tracing.'
        ),
        renderInterfaceMember(
          'method',
          'string',
          false,
          'HTTP method sent to the endpoint.'
        ),
        renderInterfaceMember(
          'url',
          'string',
          false,
          'Relative request URL including path and query string.'
        ),
        renderInterfaceMember(
          'headers',
          'Record<string, string>',
          false,
          'HTTP headers applied to the outgoing request.'
        ),
        renderInterfaceMember(
          'body',
          'TRequestBody | undefined',
          false,
          'Request body payload passed to the sender.'
        ),
      ],
      [
        {
          description: 'Request body payload type.',
          name: 'TRequestBody',
        },
      ]
    )
  );
  push();

  push(
    renderTaggedDocumentationComment(
      'Sender function used by generated accessors.',
      {
        params: [
          {
            description: 'Prepared request descriptor.',
            name: 'request',
          },
          {
            description:
              'Context value bound when creating the accessor implementation.',
            name: 'context',
          },
          {
            description: 'Abort signal used to cancel the request.',
            name: 'signal',
          },
        ],
        returns: 'Promise that resolves to the typed response payload.',
        typeParams: [
          {
            description: 'Response payload type.',
            name: 'TResponse',
          },
          {
            description: 'Request body payload type.',
            name: 'TRequestBody',
          },
          {
            description: 'Context value type passed to the sender.',
            name: 'TContext',
          },
        ],
      }
    )
  );
  push('export type AccessorSender<TContext> = <TResponse, TRequestBody>(');
  push('  request: AccessorRequestDescriptor<TRequestBody>,');
  push('  context: TContext | undefined,');
  push('  signal: AbortSignal | undefined) => Promise<TResponse>;');
  push();
  push(
    renderTaggedDocumentationComment(
      'Tuple type that controls whether a bound accessor context argument is required.',
      {
        remarks:
          'When `TContext` is `undefined`, the tuple allows the context argument to be omitted.',
        typeParams: [
          {
            description: 'Context value type passed to the sender.',
            name: 'TContext',
          },
        ],
      }
    )
  );
  push(
    'export type AccessorContextArgument<TContext> = [TContext] extends [undefined]'
  );
  push('    ? [context?: TContext]');
  push('    : [context: TContext];');
  push();
  push(
    renderInterfaceDefinition(
      'CreateFetchSenderOptions',
      'Options that configure the fetch-based sender.',
      [
        renderInterfaceMember(
          'baseUrl',
          'string | URL',
          false,
          'Base URL used to resolve generated accessor request URLs.'
        ),
        renderInterfaceMember(
          'fetch',
          'typeof fetch | undefined',
          true,
          'Fetch implementation to use. Defaults to globalThis.fetch.'
        ),
        renderInterfaceMember(
          'headers',
          'Record<string, string> | undefined',
          true,
          'Default headers merged with per-request headers.'
        ),
        renderInterfaceMember(
          'init',
          "Omit<RequestInit, 'body' | 'headers' | 'method' | 'signal'> | undefined",
          true,
          'Additional RequestInit values merged into every request. Generated accessors continue to control body, headers, method, and signal.'
        ),
      ]
    )
  );
  push();
  push(
    '/////////////////////////////////////////////////////////////////////////////////'
  );
  push();
  push("const modestaUrlBase = 'http://modesta.invalid';");
  push('const modestaJsonMediaTypePattern = /json/i;');
  push();
  push(
    'const modestaBuildUrl = (path: string, pathParameters: Record<string, unknown>, queryParameters: Record<string, unknown>) => {'
  );
  push('  let resolvedPath = path;');
  push('  for (const [key, value] of Object.entries(pathParameters)) {');
  push(
    '    resolvedPath = resolvedPath.replaceAll(`{${key}}`, encodeURIComponent(String(value)));'
  );
  push('  }');
  push('  const url = new URL(resolvedPath, modestaUrlBase);');
  push('  for (const [key, value] of Object.entries(queryParameters)) {');
  push('    if (value != null) {');
  push('      url.searchParams.set(key, String(value));');
  push('    }');
  push('  }');
  push('  return `${url.pathname}${url.search}`;');
  push('};');
  push();
  push(
    'const modestaBuildHeaders = (headerParameters: Record<string, unknown>, contentType: string | undefined, accept: string | undefined) => {'
  );
  push('  const headers: Record<string, string> = {};');
  push('  for (const [key, value] of Object.entries(headerParameters)) {');
  push('    if (value != null) {');
  push('      headers[key] = String(value);');
  push('    }');
  push('  }');
  push('  if (contentType != null) {');
  push("    headers['content-type'] = contentType;");
  push('  }');
  push('  if (accept != null) {');
  push('    headers.accept = accept;');
  push('  }');
  push('  return headers;');
  push('};');
  push();
  push(
    'const modestaSerializeFetchBody = (body: unknown, contentType: string | undefined) => {'
  );
  push('  if (body == null) {');
  push('    return undefined;');
  push('  }');
  push(
    '  return contentType != null && modestaJsonMediaTypePattern.test(contentType)'
  );
  push('    ? JSON.stringify(body)');
  push('    : body;');
  push('};');
  push();
  push(
    '/////////////////////////////////////////////////////////////////////////////////'
  );
  push();
  push(
    renderTaggedDocumentationComment(
      'Creates a sender implementation backed by the fetch API.',
      {
        params: [
          {
            description: 'Options that configure the fetch-based sender.',
            name: 'options',
          },
        ],
        remarks:
          'When `options.fetch` is omitted, `globalThis.fetch` must be available.\nAccessor context values are ignored by this sender implementation.',
        returns:
          'Sender implementation that executes requests via the fetch API.',
      }
    )
  );
  push(
    'export const createFetchSender = (options: CreateFetchSenderOptions): AccessorSender<undefined> => {'
  );
  push('  const fetchImplementation = options.fetch ?? globalThis.fetch;');
  push("  if (typeof fetchImplementation !== 'function') {");
  push(
    "    throw new Error('Fetch implementation is not available. Pass CreateFetchSenderOptions.fetch explicitly.');"
  );
  push('  }');
  push();
  push(
    '  return async <TResponse, TRequestBody>(request: AccessorRequestDescriptor<TRequestBody>, _context: undefined, signal: AbortSignal | undefined) => {'
  );
  push('    const response = await fetchImplementation(');
  push('      new URL(request.url, options.baseUrl),');
  push('      {');
  push('        ...(options.init ?? {}),');
  push('        method: request.method,');
  push('        headers: {');
  push('          ...(options.headers ?? {}),');
  push('          ...request.headers,');
  push('        },');
  push(
    "        body: modestaSerializeFetchBody(request.body, request.headers['content-type']),"
  );
  push('        signal,');
  push('      }');
  push('    );');
  push();
  push('    if (response.ok === false) {');
  push('      const responseText = await response.text();');
  push('      const statusText = response.statusText.length > 0');
  push('        ? ` ${response.statusText}`');
  push("        : '';");
  push('      throw new Error(');
  push('        responseText.length > 0');
  push(
    '          ? `Fetch request failed with ${response.status}${statusText}: ${responseText}`'
  );
  push(
    '          : `Fetch request failed with ${response.status}${statusText}.`'
  );
  push('      );');
  push('    }');
  push();
  push('    const responseText = await response.text();');
  push('    if (responseText.length === 0) {');
  push('      return undefined as TResponse;');
  push('    }');
  push();
  push("    const responseContentType = response.headers.get('content-type');");
  push(
    '    return (responseContentType != null && modestaJsonMediaTypePattern.test(responseContentType)'
  );
  push('      ? JSON.parse(responseText)');
  push('      : responseText) as TResponse;');
  push('  };');
  push('};');
  push();
  push(
    '/////////////////////////////////////////////////////////////////////////////////'
  );
  push();

  if (api.schemaDefinitions.length > 0) {
    for (const schemaDefinition of api.schemaDefinitions) {
      push(renderNamedSchemaDefinition(context, schemaDefinition));
      push();
    }
  }

  for (const accessorGroup of api.accessorGroups) {
    for (const operation of accessorGroup.operations) {
      push(renderOperationDefinition(context, operation));
      push();
    }

    push(renderAccessorInterface(accessorGroup));
    push();
    push(renderAccessorFactory(accessorGroup));
    push();
  }

  return lines.join('\n').trimEnd() + '\n';
};

const renderNamedSchemaDefinition = (
  context: OpenApiContext,
  schemaDefinition: SchemaDefinition
) => {
  const schema = resolveSchemaObject(
    context.document,
    asRecord(context.componentSchemas[schemaDefinition.rawName])
  );
  return renderNamedTypeDefinition(
    context,
    schemaDefinition.typeName,
    schema,
    schemaDefinition.description
  );
};

const renderOperationDefinition = (
  context: OpenApiContext,
  operation: OperationDefinition
) => {
  const sections: string[] = [];

  if (operation.queryParameters.length > 0) {
    sections.push(
      renderParameterGroupDefinition(
        context,
        operation.queryParametersTypeName ??
          fail(
            `Missing query parameter type name for ${operation.namingSource}.`
          ),
        'Query parameters definition.',
        operation.queryParameters
      )
    );
  }
  if (operation.headerParameters.length > 0) {
    sections.push(
      renderParameterGroupDefinition(
        context,
        operation.headerParametersTypeName ??
          fail(
            `Missing header parameter type name for ${operation.namingSource}.`
          ),
        'Header parameters definition.',
        operation.headerParameters
      )
    );
  }
  if (operation.requestBody != null) {
    sections.push(
      renderNamedTypeDefinition(
        context,
        operation.requestBody.typeName,
        operation.requestBody.schema,
        operation.requestBody.schemaDescription
      )
    );
  }

  const argumentMembers: string[] = [];
  if (operation.pathParameters.length > 0) {
    for (const parameter of operation.pathParameters) {
      argumentMembers.push(
        renderInterfaceMember(
          parameter.propertyName,
          renderTypeExpression(context, parameter.schema, 1),
          parameter.required === false,
          parameter.description
        )
      );
    }
  }
  if (operation.queryParameters.length > 0) {
    argumentMembers.push(
      renderInterfaceMember(
        'queryParameters',
        operation.queryParametersTypeName ??
          fail(
            `Missing query parameter type name for ${operation.namingSource}.`
          ),
        operation.queryParameters.some((parameter) => parameter.required) ===
          false,
        'Query parameter values.'
      )
    );
  }
  if (operation.headerParameters.length > 0) {
    argumentMembers.push(
      renderInterfaceMember(
        'headerParameters',
        operation.headerParametersTypeName ??
          fail(
            `Missing header parameter type name for ${operation.namingSource}.`
          ),
        operation.headerParameters.some((parameter) => parameter.required) ===
          false,
        'Header parameter values.'
      )
    );
  }
  if (operation.requestBody != null) {
    argumentMembers.push(
      renderInterfaceMember(
        'body',
        operation.requestBody.typeName,
        operation.requestBody.required === false,
        operation.requestBody.parameterDescription ?? 'JSON request body.'
      )
    );
  }

  sections.push(
    renderInterfaceDefinition(
      operation.argumentsTypeName,
      'Endpoint argument group.',
      argumentMembers
    )
  );

  sections.push(renderResponseDefinition(context, operation.response));

  return sections.join('\n\n');
};

const renderParameterGroupDefinition = (
  context: OpenApiContext,
  typeName: string,
  description: string,
  parameters: ParameterDefinition[]
) => {
  const members = parameters.map((parameter) =>
    renderInterfaceMember(
      parameter.propertyName,
      renderTypeExpression(context, parameter.schema, 1),
      parameter.required === false,
      parameter.description
    )
  );

  return renderInterfaceDefinition(typeName, description, members);
};

const renderResponseDefinition = (
  context: OpenApiContext,
  response: ResponseDefinition
) => {
  const description = getResponseDocumentationDescription(response);
  if (response.schema == null) {
    return [
      renderDocumentationComment(description),
      `export type ${response.typeName} = void;`,
    ].join('\n');
  }

  return renderNamedTypeDefinition(
    context,
    response.typeName,
    response.schema,
    description
  );
};

const renderAccessorInterface = (accessorGroup: AccessorGroupDefinition) => {
  const members = accessorGroup.operations.map((operation) => {
    const argumentMode = getOperationArgumentMode(operation);
    const signature =
      argumentMode === 'none'
        ? `(signal?: AbortSignal | undefined) => Promise<${getOperationResponseTypeExpression(operation.response)}>`
        : `(${[
            argumentMode === 'required'
              ? `args: ${operation.argumentsTypeName}`
              : `args?: ${operation.argumentsTypeName} | undefined`,
            'signal?: AbortSignal | undefined',
          ].join(
            ', '
          )}) => Promise<${getOperationResponseTypeExpression(operation.response)}>`;
    const argumentDescription =
      argumentMode === 'none'
        ? undefined
        : argumentMode === 'required'
          ? `Arguments for ${operation.method} ${operation.path}.`
          : `Optional arguments for ${operation.method} ${operation.path}.`;
    return [
      renderOperationDocumentationComment(
        operation.summary,
        operation.description,
        `${operation.method} ${operation.path}`,
        argumentDescription,
        getResponseDocumentationDescription(operation.response)
      ),
      `  readonly ${renderPropertyName(operation.memberName)}: ${signature};`,
    ].join('\n');
  });

  return renderInterfaceDefinition(
    accessorGroup.interfaceName,
    `${accessorGroup.interfaceName} accessor definition.`,
    members
  );
};

const renderAccessorFactory = (accessorGroup: AccessorGroupDefinition) => {
  const lines: string[] = [];
  const push = (value = '') => {
    lines.push(value);
  };

  push(
    renderTaggedDocumentationComment(
      `Creates a ${accessorGroup.interfaceName} accessor implementation.`,
      {
        params: [
          {
            description:
              'Sender implementation used to execute generated requests.',
            name: 'sender',
          },
          {
            description:
              'Context value passed to the sender for every accessor call. This may be ignored depending on the sender.',
            name: 'context',
          },
        ],
        remarks:
          'The context argument can be omitted only when `TContext` is `undefined`.',
        typeParams: [
          {
            description: 'Context value type passed to the sender.',
            name: 'TContext',
          },
        ],
        returns: `${accessorGroup.interfaceName} accessor implementation bound to the provided sender.`,
      }
    )
  );
  push(`export const ${accessorGroup.factoryName} = <TContext>(`);
  push('  sender: AccessorSender<TContext>,');
  push('  ...[context]: AccessorContextArgument<TContext>');
  push(`): ${accessorGroup.interfaceName} => ({`);

  for (const operation of accessorGroup.operations) {
    const argumentMode = getOperationArgumentMode(operation);
    const argumentToken =
      argumentMode === 'none'
        ? 'signal'
        : argumentMode === 'required'
          ? 'args, signal'
          : 'args, signal';

    push(
      `  ${renderPropertyName(operation.memberName)}: async (${argumentToken}) => sender<${getOperationResponseTypeExpression(operation.response)}, ${operation.requestBody?.typeName ?? 'undefined'}>({`
    );
    push(
      `    operationName: ${renderLiteral(operation.descriptorOperationName)},`
    );
    push(`    method: ${renderLiteral(operation.method)},`);
    push(
      `    url: modestaBuildUrl(${[
        renderLiteral(operation.path),
        renderPathParameterArgumentObject(operation),
        operation.queryParameters.length > 0
          ? argumentMode === 'optional'
            ? 'args?.queryParameters ?? {}'
            : 'args.queryParameters ?? {}'
          : '{}',
      ].join(', ')}),`
    );
    push(
      `    headers: modestaBuildHeaders(${operation.headerParameters.length > 0 ? (argumentMode === 'optional' ? 'args?.headerParameters ?? {}' : 'args.headerParameters ?? {}') : '{}'}, ${operation.requestBody?.contentType != null ? renderLiteral(operation.requestBody.contentType) : 'undefined'}, ${operation.response.accept != null ? renderLiteral(operation.response.accept) : 'undefined'}),`
    );
    push(
      `    body: ${operation.requestBody != null ? (argumentMode === 'optional' ? 'args?.body' : 'args.body') : 'undefined'},`
    );
    push('  }, context, signal),');
  }

  push('});');
  return lines.join('\n');
};

const renderNamedTypeDefinition = (
  context: OpenApiContext,
  typeName: string,
  schema: JsonRecord,
  description: string | undefined
) => {
  const flattened = tryFlattenObjectSchema(context, schema, new Set<string>());
  if (flattened != null) {
    const members = flattened.properties.map((property) =>
      renderInterfaceMember(
        property.propertyName,
        renderTypeExpression(context, property.schema, 1),
        property.required === false,
        property.description
      )
    );
    if (flattened.additionalPropertiesType != null) {
      members.push(
        `  readonly [key: string]: ${flattened.additionalPropertiesType};`
      );
    }
    return renderInterfaceDefinition(typeName, description, members);
  }

  return [
    renderDocumentationComment(description),
    `export type ${typeName} = ${renderTypeExpression(context, schema, 0)};`,
  ].join('\n');
};

const renderInterfaceDefinition = (
  name: string,
  description: string | undefined,
  members: string[],
  typeParams:
    | { description: string | undefined; name: string }[]
    | undefined = undefined
) => {
  const lines: string[] = [];
  lines.push(
    typeParams != null
      ? renderTaggedDocumentationComment(description, { typeParams })
      : renderDocumentationComment(description)
  );
  lines.push(`export interface ${name} {`);
  if (members.length === 0) {
    lines.push('}');
    return lines.join('\n');
  }

  for (const member of members) {
    lines.push(member);
  }
  lines.push('}');
  return lines.join('\n');
};

const renderInterfaceMember = (
  name: string,
  type: string,
  optional: boolean,
  description: string | undefined,
  readonly = true
) => {
  const lines: string[] = [];
  if (description != null) {
    lines.push(indent(renderDocumentationComment(description), 1));
  }
  lines.push(
    `  ${readonly ? 'readonly ' : ''}${renderPropertyName(name)}${optional ? '?' : ''}: ${type};`
  );
  return lines.join('\n');
};

const renderDocumentationComment = (description: string | undefined) => {
  const lines = normalizeDocumentationLines(
    description,
    'Generated definition.'
  );
  if (lines.length === 0) {
    return '/** Generated definition. */';
  }

  if (lines.length === 1) {
    return `/** ${lines[0]} */`;
  }

  return ['/**', ...lines.map((line) => ` * ${line}`), ' */'].join('\n');
};

const normalizeDocumentationLines = (
  description: string | undefined,
  fallback: string
) =>
  (description ?? fallback)
    .split(/\r?\n/u)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

const appendTaggedDocumentationLines = (
  lines: string[],
  tagName: 'param' | 'remarks' | 'returns' | 'typeParam',
  tagValue: string,
  description: string | undefined
) => {
  const normalizedLines = normalizeDocumentationLines(description, tagValue);
  if (normalizedLines.length === 0) {
    return;
  }

  const tagPrefix =
    tagValue.length > 0 ? ` * @${tagName} ${tagValue}` : ` * @${tagName}`;
  lines.push(`${tagPrefix} ${normalizedLines[0]}`);
  for (const line of normalizedLines.slice(1)) {
    lines.push(` * ${line}`);
  }
};

const renderTaggedDocumentationComment = (
  description: string | undefined,
  options: {
    params?: { description: string | undefined; name: string }[] | undefined;
    remarks?: string | undefined;
    returns?: string | undefined;
    typeParams?:
      | { description: string | undefined; name: string }[]
      | undefined;
  }
) => {
  const lines = ['/**'];
  lines.push(
    ...normalizeDocumentationLines(description, 'Generated definition.').map(
      (line) => ` * ${line}`
    )
  );

  for (const typeParam of options.typeParams ?? []) {
    appendTaggedDocumentationLines(
      lines,
      'typeParam',
      typeParam.name,
      typeParam.description
    );
  }
  for (const parameter of options.params ?? []) {
    appendTaggedDocumentationLines(
      lines,
      'param',
      parameter.name,
      parameter.description
    );
  }
  if (options.returns != null) {
    appendTaggedDocumentationLines(lines, 'returns', '', options.returns);
  }
  if (options.remarks != null) {
    appendTaggedDocumentationLines(lines, 'remarks', '', options.remarks);
  }

  lines.push(' */');
  return lines.join('\n');
};

const renderPathParameterArgumentObject = (operation: OperationDefinition) => {
  if (operation.pathParameters.length === 0) {
    return '{}';
  }

  return [
    '{',
    ...operation.pathParameters.map(
      (parameter) =>
        `  ${renderPropertyName(parameter.propertyName)}: args[${renderLiteral(parameter.propertyName)}],`
    ),
    '}',
  ].join('\n');
};

const renderOperationDocumentationComment = (
  summary: string | undefined,
  remarks: string | undefined,
  fallback: string,
  argumentDescription: string | undefined,
  returnDescription: string
) => {
  const normalizedSummary = summary?.trim();
  const normalizedRemarks = remarks?.trim();
  const descriptionLines = normalizeDocumentationLines(
    normalizedSummary != null && normalizedSummary.length > 0
      ? summary
      : remarks,
    fallback
  );

  if (descriptionLines.length === 0) {
    return renderDocumentationComment(fallback);
  }

  const lines = ['/**', ...descriptionLines.map((line) => ` * ${line}`)];
  const hasDistinctRemarks =
    normalizedSummary != null &&
    normalizedSummary.length > 0 &&
    normalizedRemarks != null &&
    normalizedRemarks.length > 0 &&
    normalizedRemarks !== normalizedSummary;

  if (hasDistinctRemarks) {
    lines.push(' *');
    appendTaggedDocumentationLines(lines, 'remarks', '', remarks);
  }

  if (argumentDescription != null) {
    appendTaggedDocumentationLines(lines, 'param', 'args', argumentDescription);
  }
  appendTaggedDocumentationLines(
    lines,
    'param',
    'signal',
    'Abort signal used to cancel the request.'
  );
  appendTaggedDocumentationLines(lines, 'returns', '', returnDescription);
  lines.push(' */');

  return lines.join('\n');
};

const getResponseDocumentationDescription = (response: ResponseDefinition) =>
  response.description ?? `Response type for HTTP ${response.statusCode}.`;

const getOperationArgumentMode = (operation: OperationDefinition) => {
  const hasArguments =
    operation.pathParameters.length > 0 ||
    operation.queryParameters.length > 0 ||
    operation.headerParameters.length > 0 ||
    operation.requestBody != null;
  if (hasArguments === false) {
    return 'none' as const;
  }

  const requiresArguments =
    operation.pathParameters.some((parameter) => parameter.required) ||
    operation.queryParameters.some((parameter) => parameter.required) ||
    operation.headerParameters.some((parameter) => parameter.required) ||
    (operation.requestBody?.required ?? false);
  return requiresArguments ? ('required' as const) : ('optional' as const);
};

const getOperationResponseTypeExpression = (response: ResponseDefinition) =>
  response.schema == null ? 'void' : response.typeName;

const renderTypeExpression = (
  context: OpenApiContext,
  schema: JsonRecord,
  indentLevel: number
): string => {
  if (hasUnsupportedComposition(schema)) {
    throw new Error(
      'Unsupported schema composition detected. oneOf/anyOf/discriminator is not supported.'
    );
  }

  const nullable = getBoolean(schema, 'nullable') ?? false;
  let coreType: string;
  const directReference = getDirectReference(schema);
  const allOfReference = getSingleReferenceFromAllOf(schema);

  if (directReference != null && isReferenceWrapperSchema(schema)) {
    coreType = resolveReferenceTypeName(context, directReference);
  } else if (allOfReference != null && isAllOfReferenceWrapperSchema(schema)) {
    coreType = resolveReferenceTypeName(context, allOfReference);
  } else if (asArray(schema.allOf) != null) {
    const flattened = tryFlattenObjectSchema(
      context,
      schema,
      new Set<string>()
    );
    if (flattened != null) {
      coreType = renderInlineObjectType(flattened, indentLevel);
    } else {
      coreType = asArray(schema.allOf)!
        .map((entry) =>
          renderTypeExpression(
            context,
            resolveSchemaObject(context.document, asRecord(entry)),
            indentLevel
          )
        )
        .join(' & ');
    }
  } else if (asArray(schema.enum) != null) {
    coreType = renderEnumType(asArray(schema.enum)!);
  } else {
    const typeName = getString(schema, 'type');
    switch (typeName) {
      case 'string':
        coreType = 'string';
        break;
      case 'number':
      case 'integer':
        coreType = 'number';
        break;
      case 'boolean':
        coreType = 'boolean';
        break;
      case 'array':
        coreType = `Array<${renderTypeExpression(
          context,
          resolveSchemaObject(
            context.document,
            getRequiredRecord(schema, 'items', 'array items')
          ),
          indentLevel
        )}>`;
        break;
      case 'object':
      default:
        if (isObjectSchema(schema)) {
          const flattened = tryFlattenObjectSchema(
            context,
            schema,
            new Set<string>()
          );
          if (flattened == null) {
            throw new Error('Could not flatten object schema.');
          }
          coreType = renderInlineObjectType(flattened, indentLevel);
          break;
        }

        if (typeName == null) {
          coreType = 'unknown';
          break;
        }

        throw new Error(`Unsupported schema type: ${typeName}`);
    }
  }

  return nullable ? `${coreType} | null` : coreType;
};

const renderEnumType = (values: unknown[]) => {
  const normalized = values.map((value) => renderLiteral(value));
  return normalized.join(' | ');
};

const renderInlineObjectType = (
  flattened: FlattenedObjectSchema,
  indentLevel: number
) => {
  const members: string[] = [];
  for (const property of flattened.properties) {
    if (property.description != null) {
      members.push(indent(renderDocumentationComment(property.description), 1));
    }
    members.push(
      `  ${renderPropertyName(property.propertyName)}${property.required ? '' : '?'}: ${property.typeExpression};`
    );
  }
  if (flattened.additionalPropertiesType != null) {
    members.push(`  [key: string]: ${flattened.additionalPropertiesType};`);
  }

  if (members.length === 0) {
    return 'Record<string, never>';
  }

  return `{\n${indent(members.join('\n'), indentLevel)}\n${'  '.repeat(indentLevel)}}`;
};

interface FlattenedProperty {
  description: string | undefined;
  propertyName: string;
  required: boolean;
  schema: JsonRecord;
  typeExpression: string;
}

interface FlattenedObjectSchema {
  additionalPropertiesType: string | undefined;
  properties: FlattenedProperty[];
}

const tryFlattenObjectSchema = (
  context: OpenApiContext,
  schema: JsonRecord,
  visitedReferences: Set<string>
): FlattenedObjectSchema | undefined => {
  const expanded = expandObjectShape(context, schema, visitedReferences);
  if (expanded == null) {
    return undefined;
  }

  return {
    additionalPropertiesType:
      expanded.additionalPropertiesSchema != null
        ? renderTypeExpression(context, expanded.additionalPropertiesSchema, 1)
        : undefined,
    properties: expanded.properties
      .sort((left, right) => left.name.localeCompare(right.name))
      .map((property) => ({
        description: property.description,
        propertyName: property.name,
        required: property.required,
        schema: property.schema,
        typeExpression: renderTypeExpression(context, property.schema, 1),
      })),
  };
};

interface ExpandedProperty {
  description: string | undefined;
  name: string;
  required: boolean;
  schema: JsonRecord;
}

interface ExpandedObjectShape {
  additionalPropertiesSchema: JsonRecord | undefined;
  properties: ExpandedProperty[];
}

const expandObjectShape = (
  context: OpenApiContext,
  schema: JsonRecord,
  visitedReferences: Set<string>
): ExpandedObjectShape | undefined => {
  if (hasUnsupportedComposition(schema)) {
    throw new Error(
      'Unsupported schema composition detected. oneOf/anyOf/discriminator is not supported.'
    );
  }

  if (isPureReference(schema)) {
    const reference = getRequiredString(schema, '$ref', '$ref');
    if (visitedReferences.has(reference)) {
      throw new Error(
        `Circular object schema reference is not supported in flattening: ${reference}`
      );
    }
    visitedReferences.add(reference);
    const resolved = resolveReferenceObject(context.document, schema);
    const expanded = expandObjectShape(
      context,
      resolved ?? schema,
      visitedReferences
    );
    visitedReferences.delete(reference);
    return expanded;
  }

  const allOf = asArray(schema.allOf);
  if (allOf != null) {
    const mergedProperties = new Map<string, ExpandedProperty>();
    let additionalPropertiesSchema: JsonRecord | undefined;
    for (const entry of allOf) {
      const expanded = expandObjectShape(
        context,
        resolveSchemaObject(context.document, asRecord(entry)),
        visitedReferences
      );
      if (expanded == null) {
        return undefined;
      }

      for (const property of expanded.properties) {
        mergedProperties.set(property.name, property);
      }

      if (expanded.additionalPropertiesSchema != null) {
        additionalPropertiesSchema = expanded.additionalPropertiesSchema;
      }
    }

    const direct = expandDirectObjectShape(context, schema);
    if (direct != null) {
      for (const property of direct.properties) {
        mergedProperties.set(property.name, property);
      }
      if (direct.additionalPropertiesSchema != null) {
        additionalPropertiesSchema = direct.additionalPropertiesSchema;
      }
    }

    return {
      additionalPropertiesSchema,
      properties: Array.from(mergedProperties.values()),
    };
  }

  return expandDirectObjectShape(context, schema);
};

const expandDirectObjectShape = (
  context: OpenApiContext,
  schema: JsonRecord
): ExpandedObjectShape | undefined => {
  if (isObjectSchema(schema) === false) {
    return undefined;
  }

  const properties = getRecord(schema, 'properties') ?? {};
  const requiredNames = new Set(
    (asArray(schema.required) ?? [])
      .map((name) => (typeof name === 'string' ? name : undefined))
      .filter((name): name is string => name != null)
  );

  const expandedProperties = Object.keys(properties).map((propertyName) => {
    const propertySchema = asRecord(properties[propertyName]);
    if (propertySchema == null) {
      throw new Error(`Could not resolve property schema: ${propertyName}`);
    }
    const resolvedPropertySchema = resolveSchemaObject(
      context.document,
      propertySchema
    );
    return {
      description:
        getString(propertySchema, 'description') ??
        getString(resolvedPropertySchema, 'description'),
      name: propertyName,
      required: requiredNames.has(propertyName),
      schema: propertySchema,
    } satisfies ExpandedProperty;
  });

  const rawAdditionalProperties = schema.additionalProperties;
  let additionalPropertiesSchema: JsonRecord | undefined;
  if (rawAdditionalProperties === true) {
    additionalPropertiesSchema = {};
  } else {
    const additionalPropertiesRecord = asRecord(rawAdditionalProperties);
    if (additionalPropertiesRecord != null) {
      additionalPropertiesSchema = additionalPropertiesRecord;
    }
  }

  return {
    additionalPropertiesSchema,
    properties: expandedProperties,
  };
};

const isObjectSchema = (schema: JsonRecord) => {
  if (getString(schema, 'type') === 'object') {
    return true;
  }
  if (getRecord(schema, 'properties') != null) {
    return true;
  }
  if (schema.additionalProperties != null) {
    return true;
  }
  if (asArray(schema.allOf) != null) {
    return true;
  }
  return false;
};

const hasUnsupportedComposition = (schema: JsonRecord) => {
  return (
    asArray(schema.oneOf) != null ||
    asArray(schema.anyOf) != null ||
    getRecord(schema, 'discriminator') != null
  );
};

const resolveReferenceTypeName = (
  context: OpenApiContext,
  reference: string
) => {
  const match = /^#\/components\/schemas\/(.+)$/u.exec(reference);
  if (match == null) {
    const resolved = resolveReferenceObject(context.document, {
      $ref: reference,
    });
    return renderTypeExpression(context, resolved ?? {}, 0);
  }

  const mapped = context.naming.schemaTypeNames.get(match[1]);
  if (mapped == null) {
    throw new Error(`Unknown schema reference: ${reference}`);
  }
  return mapped;
};
