// modesta - Simplest zero-dependency swagger proxy generator
// Copyright (c) Kouji Matsui (@kekyo@mi.kekyo.net)
// Under MIT.
// https://github.com/kekyo/modesta/

import { JsonRecord } from '../types';
import {
  AccessorGroupDefinition,
  ApiDefinition,
  OpenApiContext,
  OperationDefinition,
  ParameterDefinition,
  RequestBodyDefinition,
  ResponseDefinition,
  ResponseHeaderDefinition,
  SchemaDefinition,
} from './types';
import {
  isSchemaObjectLike,
  resolveReferenceObject,
  resolveSchemaDeprecated,
  resolveSchemaObject,
} from './resolve';
import {
  asArray,
  asRecord,
  fail,
  getBoolean,
  getDirectReference,
  getRecord,
  getRequiredRecord,
  getRequiredString,
  getSingleReferenceFromAllOf,
  getString,
  indent,
  isAllOfReferenceWrapperSchema,
  isPureReference,
  isReferenceWrapperSchema,
  normalizeValueName,
  renderLiteral,
  renderPropertyName,
} from '../util';
import { version } from '../generated/packageMetadata';
import { basename } from 'path';
import { fileURLToPath } from 'url';
import runtimeSource from '../assets/runtime.ts?raw';

//////////////////////////////////////////////////////////////////////////

const anonymizeSourceFileDisplay = (source: string) => {
  try {
    const url = new URL(source);
    if (url.protocol === 'file:') {
      return basename(fileURLToPath(url));
    }
    if (url.protocol !== 'http:' && url.protocol !== 'https:') {
      return source;
    }

    url.hostname = 'example.com';
    url.port = '';
    url.username = '';
    url.password = '';
    return url.href;
  } catch {
    return basename(source);
  }
};

export const renderApiDefinition = (
  api: ApiDefinition,
  context: OpenApiContext
) => {
  const lines: string[] = [];
  const push = (value = '') => {
    lines.push(value);
  };
  const schemaMetadata = createSchemaMetadataRegistry(context, api);

  push('// @ts-nocheck');
  push(`// This file is auto-generated by modesta [${version}]`);
  push('// Do not edit manually');

  if (api.title != null) {
    push(`// Source title: ${api.title}`);
  }
  if (api.source != null) {
    push(`// Source file: ${anonymizeSourceFileDisplay(api.source)}`);
  }
  push();
  push(runtimeSource.trimEnd());
  push();
  const renderedSchemaMetadata = schemaMetadata.renderDefinitions();
  if (renderedSchemaMetadata.length > 0) {
    push(renderedSchemaMetadata);
    push();
  }

  if (api.schemaDefinitions.length > 0) {
    for (const schemaDefinition of api.schemaDefinitions) {
      push(renderNamedSchemaDefinition(context, schemaDefinition));
      push();
    }
  }

  for (const accessorGroup of api.accessorGroups) {
    for (const operation of accessorGroup.operations) {
      const renderedOperationDefinition = renderOperationDefinition(
        context,
        operation
      );
      if (renderedOperationDefinition.length > 0) {
        push(renderedOperationDefinition);
        push();
      }
    }

    push(renderAccessorInterfaces(context, accessorGroup));
    push();
    push(renderAccessorFactory(context, accessorGroup, schemaMetadata));
    push();
  }

  return lines.join('\n').trimEnd() + '\n';
};

interface SchemaMetadataRegistry {
  getRequestBodyMetadataName: (
    operation: OperationDefinition
  ) => string | undefined;
  getResponseBodyMetadataName: (
    operation: OperationDefinition
  ) => string | undefined;
  renderDefinitions: () => string;
}

interface SchemaMetadataProperty {
  metadata: SchemaMetadataNode;
  name: string;
}

interface SchemaMetadataNode {
  additionalProperties: SchemaMetadataNode | undefined;
  format: string | undefined;
  items: SchemaMetadataNode | undefined;
  preferredName: string;
  properties: readonly SchemaMetadataProperty[];
}

const createSchemaMetadataRegistry = (
  context: OpenApiContext,
  api: ApiDefinition
): SchemaMetadataRegistry => {
  const definitions: string[] = [];
  const metadataNamesBySignature = new Map<string, string>();
  const usedMetadataNames = new Set<string>();
  const requestBodyMetadataNames = new Map<string, string>();
  const responseBodyMetadataNames = new Map<string, string>();

  const reserveMetadataName = (preferredName: string) => {
    const normalized = normalizeValueName(
      preferredName,
      'modestaSchemaMetadata'
    );
    let candidate = normalized;
    let suffix = 2;
    while (usedMetadataNames.has(candidate)) {
      candidate = `${normalized}_${suffix}`;
      suffix += 1;
    }
    usedMetadataNames.add(candidate);
    return candidate;
  };

  const getSignature = (metadata: SchemaMetadataNode): string =>
    JSON.stringify({
      additionalProperties:
        metadata.additionalProperties != null
          ? getSignature(metadata.additionalProperties)
          : undefined,
      format: metadata.format,
      items: metadata.items != null ? getSignature(metadata.items) : undefined,
      properties: metadata.properties.map((property) => [
        property.name,
        getSignature(property.metadata),
      ]),
    });

  const renderMetadataObject = (
    metadata: SchemaMetadataNode,
    propertyNames: readonly { constName: string; name: string }[],
    itemsName: string | undefined,
    additionalPropertiesName: string | undefined
  ) => {
    const lines = ['{'];
    if (metadata.format != null) {
      lines.push(`  format: ${renderLiteral(metadata.format)},`);
    }
    if (propertyNames.length > 0) {
      lines.push('  properties: {');
      for (const property of propertyNames) {
        lines.push(
          `    ${renderPropertyName(property.name)}: ${property.constName},`
        );
      }
      lines.push('  },');
    }
    if (itemsName != null) {
      lines.push(`  items: ${itemsName},`);
    }
    if (additionalPropertiesName != null) {
      lines.push(`  additionalProperties: ${additionalPropertiesName},`);
    }
    lines.push('}');
    return lines.join('\n');
  };

  const renderMetadataDefinition = (metadata: SchemaMetadataNode): string => {
    const signature = getSignature(metadata);
    const existingName = metadataNamesBySignature.get(signature);
    if (existingName != null) {
      return existingName;
    }

    const propertyNames = metadata.properties.map((property) => ({
      constName: renderMetadataDefinition(property.metadata),
      name: property.name,
    }));
    const itemsName =
      metadata.items != null
        ? renderMetadataDefinition(metadata.items)
        : undefined;
    const additionalPropertiesName =
      metadata.additionalProperties != null
        ? renderMetadataDefinition(metadata.additionalProperties)
        : undefined;
    const preferredName =
      metadata.format != null &&
      propertyNames.length === 0 &&
      itemsName == null &&
      additionalPropertiesName == null
        ? `modestaSchemaMetadata_format_${metadata.format}`
        : metadata.preferredName;
    const constName = reserveMetadataName(preferredName);
    definitions.push(
      `const ${constName}: AccessorSchemaMetadata = ${renderMetadataObject(
        metadata,
        propertyNames,
        itemsName,
        additionalPropertiesName
      )};`
    );
    metadataNamesBySignature.set(signature, constName);
    return constName;
  };

  const registerSchemaMetadata = (
    schema: JsonRecord,
    preferredName: string
  ) => {
    const metadata = collectSchemaMetadata(
      context,
      schema,
      preferredName,
      new Set<string>()
    );
    return metadata != null ? renderMetadataDefinition(metadata) : undefined;
  };

  for (const accessorGroup of api.accessorGroups) {
    for (const operation of accessorGroup.operations) {
      if (operation.requestBody != null) {
        const metadataName = registerSchemaMetadata(
          operation.requestBody.schema,
          `modestaSchemaMetadata_${accessorGroup.interfaceName}_${operation.memberName}_requestBody`
        );
        if (metadataName != null) {
          requestBodyMetadataNames.set(
            operation.descriptorOperationName,
            metadataName
          );
        }
      }
      if (operation.response.schema != null) {
        const metadataName = registerSchemaMetadata(
          operation.response.schema,
          `modestaSchemaMetadata_${accessorGroup.interfaceName}_${operation.memberName}_responseBody`
        );
        if (metadataName != null) {
          responseBodyMetadataNames.set(
            operation.descriptorOperationName,
            metadataName
          );
        }
      }
    }
  }

  return {
    getRequestBodyMetadataName: (operation) =>
      requestBodyMetadataNames.get(operation.descriptorOperationName),
    getResponseBodyMetadataName: (operation) =>
      responseBodyMetadataNames.get(operation.descriptorOperationName),
    renderDefinitions: () => definitions.join('\n\n'),
  };
};

const getSchemaMetadataComponentName = (
  context: OpenApiContext,
  reference: string
) => {
  const prefix = '#/components/schemas/';
  if (reference.startsWith(prefix) === false) {
    return undefined;
  }

  const rawName = reference
    .slice(prefix.length)
    .replaceAll('~1', '/')
    .replaceAll('~0', '~');
  const typeName = context.naming.schemaTypeNames.get(rawName);
  return typeName != null ? `modestaSchemaMetadata_${typeName}` : undefined;
};

const getSchemaMetadataChildName = (
  preferredName: string,
  childName: string,
  fallback: string
) =>
  normalizeValueName(
    `${preferredName}_${childName}`,
    `${preferredName}_${fallback}`
  );

const mergeSchemaMetadataNode = (
  preferredName: string,
  left: SchemaMetadataNode | undefined,
  right: SchemaMetadataNode | undefined
): SchemaMetadataNode | undefined => {
  if (left == null) {
    return right != null
      ? {
          ...right,
          preferredName,
        }
      : undefined;
  }
  if (right == null) {
    return left;
  }

  const properties = new Map<string, SchemaMetadataNode>();
  for (const property of left.properties) {
    properties.set(property.name, property.metadata);
  }
  for (const property of right.properties) {
    properties.set(property.name, property.metadata);
  }

  return {
    additionalProperties:
      right.additionalProperties ?? left.additionalProperties,
    format: right.format ?? left.format,
    items: right.items ?? left.items,
    preferredName,
    properties: Array.from(properties.entries())
      .sort(([leftName], [rightName]) => leftName.localeCompare(rightName))
      .map(([name, metadata]) => ({
        metadata,
        name,
      })),
  };
};

const collectSchemaMetadata = (
  context: OpenApiContext,
  schema: JsonRecord,
  preferredName: string,
  visitedReferences: Set<string>
): SchemaMetadataNode | undefined => {
  if (isPureReference(schema)) {
    const reference = getRequiredString(schema, '$ref', '$ref');
    if (visitedReferences.has(reference)) {
      return undefined;
    }

    visitedReferences.add(reference);
    const resolved = resolveReferenceObject(context.document, schema);
    const metadata =
      resolved != null
        ? collectSchemaMetadata(
            context,
            resolved,
            getSchemaMetadataComponentName(context, reference) ?? preferredName,
            visitedReferences
          )
        : undefined;
    visitedReferences.delete(reference);
    return metadata;
  }

  const allOfReference = getSingleReferenceFromAllOf(schema);
  if (allOfReference != null && isAllOfReferenceWrapperSchema(schema)) {
    return collectSchemaMetadata(
      context,
      { $ref: allOfReference },
      getSchemaMetadataComponentName(context, allOfReference) ?? preferredName,
      visitedReferences
    );
  }

  let mergedMetadata: SchemaMetadataNode | undefined;
  const allOf = asArray(schema.allOf);
  if (allOf != null) {
    for (const entry of allOf) {
      const entrySchema = asRecord(entry);
      if (entrySchema == null) {
        continue;
      }
      mergedMetadata = mergeSchemaMetadataNode(
        preferredName,
        mergedMetadata,
        collectSchemaMetadata(
          context,
          entrySchema,
          preferredName,
          visitedReferences
        )
      );
    }
  }

  const properties = getRecord(schema, 'properties');
  const propertyMetadata: SchemaMetadataProperty[] = [];
  if (properties != null) {
    for (const propertyName of Object.keys(properties).sort()) {
      const propertySchema = asRecord(properties[propertyName]);
      if (propertySchema == null) {
        continue;
      }
      const metadata = collectSchemaMetadata(
        context,
        propertySchema,
        getSchemaMetadataChildName(preferredName, propertyName, 'property'),
        visitedReferences
      );
      if (metadata != null) {
        propertyMetadata.push({
          metadata,
          name: propertyName,
        });
      }
    }
  }

  const itemsSchema = getRecord(schema, 'items');
  const itemsMetadata =
    itemsSchema != null
      ? collectSchemaMetadata(
          context,
          itemsSchema,
          getSchemaMetadataChildName(preferredName, 'items', 'items'),
          visitedReferences
        )
      : undefined;
  const additionalPropertiesSchema =
    typeof schema.additionalProperties === 'object'
      ? asRecord(schema.additionalProperties)
      : undefined;
  const additionalPropertiesMetadata =
    additionalPropertiesSchema != null
      ? collectSchemaMetadata(
          context,
          additionalPropertiesSchema,
          getSchemaMetadataChildName(
            preferredName,
            'additionalProperties',
            'additionalProperties'
          ),
          visitedReferences
        )
      : undefined;
  const directMetadata: SchemaMetadataNode | undefined =
    getString(schema, 'format') != null ||
    propertyMetadata.length > 0 ||
    itemsMetadata != null ||
    additionalPropertiesMetadata != null
      ? {
          additionalProperties: additionalPropertiesMetadata,
          format: getString(schema, 'format'),
          items: itemsMetadata,
          preferredName,
          properties: propertyMetadata,
        }
      : undefined;

  return mergeSchemaMetadataNode(preferredName, mergedMetadata, directMetadata);
};

const renderNamedSchemaDefinition = (
  context: OpenApiContext,
  schemaDefinition: SchemaDefinition
) => {
  const schema = asRecord(context.componentSchemas[schemaDefinition.rawName]);
  if (schema == null) {
    throw new Error(
      `Could not resolve schema '${schemaDefinition.rawName}' for rendering.`
    );
  }
  return renderNamedTypeDefinition(
    context,
    schemaDefinition.typeName,
    schema,
    schemaDefinition.description
  );
};

const renderOperationDefinition = (
  context: OpenApiContext,
  operation: OperationDefinition
) => {
  const sections: string[] = [];

  if (
    operation.requestBody != null &&
    shouldRenderOperationSchemaDefinition(context, operation.requestBody.schema)
  ) {
    sections.push(
      renderNamedTypeDefinition(
        context,
        operation.requestBody.typeName,
        operation.requestBody.schema,
        operation.requestBody.schemaDescription
      )
    );
  }
  const renderedRequestBodyEnvelopeDefinition =
    renderRequestBodyEnvelopeDefinition(context, operation);
  if (renderedRequestBodyEnvelopeDefinition != null) {
    sections.push(renderedRequestBodyEnvelopeDefinition);
  }

  const argumentMembers: string[] = [];
  for (const parameter of getOperationParameters(operation)) {
    argumentMembers.push(
      renderInterfaceMember(
        parameter.propertyName,
        renderTypeExpression(context, parameter.schema, 1),
        parameter.required === false,
        parameter.description,
        parameter.deprecated ? 'This argument is deprecated.' : undefined,
        true,
        parameter.duplicatedPropertyName != null
          ? `Duplicated argument name: '${parameter.duplicatedPropertyName}'`
          : undefined
      )
    );
  }

  if (argumentMembers.length > 0) {
    sections.push(
      renderInterfaceDefinition(
        operation.argumentsTypeName,
        'Flattened endpoint parameter arguments.',
        argumentMembers
      )
    );
  }

  for (const renderedResponseDefinition of renderResponseDefinitions(
    context,
    operation.response
  )) {
    sections.push(renderedResponseDefinition);
  }

  return sections.join('\n\n');
};

const renderRequestBodyEnvelopeDefinition = (
  context: OpenApiContext,
  operation: OperationDefinition
) => {
  const requestBody = operation.requestBody;
  if (
    requestBody == null ||
    shouldUseRequestBodyEnvelope(context, operation) === false
  ) {
    return undefined;
  }

  return renderInterfaceDefinition(
    requestBody.envelopeTypeName ??
      fail(`Missing request envelope type for ${requestBody.typeName}.`),
    'Request body envelope used when the payload cannot be flattened into top-level arguments.',
    [
      renderInterfaceMember(
        'body',
        getOperationRequestBodyTypeExpression(context, requestBody),
        requestBody.required === false,
        requestBody.parameterDescription,
        resolveSchemaDeprecated(context.document, requestBody.schema)
          ? 'This request body is deprecated.'
          : undefined
      ),
    ]
  );
};

const renderResponseDefinitions = (
  context: OpenApiContext,
  response: ResponseDefinition
) => {
  const sections: string[] = [];

  if (
    response.schema != null &&
    shouldRenderOperationSchemaDefinition(context, response.schema)
  ) {
    sections.push(
      renderNamedTypeDefinition(
        context,
        response.typeName,
        response.schema,
        getResponseDocumentationDescription(response)
      )
    );
  }

  const renderedResponseHeadersDefinition = renderResponseHeadersDefinition(
    context,
    response
  );
  if (renderedResponseHeadersDefinition != null) {
    sections.push(renderedResponseHeadersDefinition);
  }

  const renderedResponseBodyEnvelopeDefinition =
    renderResponseBodyEnvelopeDefinition(context, response);
  if (renderedResponseBodyEnvelopeDefinition != null) {
    sections.push(renderedResponseBodyEnvelopeDefinition);
  }

  return sections;
};

const renderResponseHeadersDefinition = (
  context: OpenApiContext,
  response: ResponseDefinition
) => {
  if (response.headers.length === 0) {
    return undefined;
  }

  return renderInterfaceDefinition(
    response.headersTypeName ??
      fail(`Missing response headers type for ${response.typeName}.`),
    `Response header values projected from HTTP ${response.statusCode}.`,
    response.headers.map((header) =>
      renderInterfaceMember(
        header.propertyName,
        renderTypeExpression(context, header.schema, 1),
        header.required === false,
        header.description,
        header.deprecated ? 'This response header is deprecated.' : undefined,
        true,
        header.duplicatedPropertyName != null
          ? `Duplicated response field name: '${header.duplicatedPropertyName}'`
          : undefined
      )
    )
  );
};

const renderResponseBodyEnvelopeDefinition = (
  context: OpenApiContext,
  response: ResponseDefinition
) => {
  if (shouldUseResponseBodyEnvelope(context, response) === false) {
    return undefined;
  }

  return renderInterfaceDefinition(
    response.bodyEnvelopeTypeName ??
      fail(`Missing response body envelope type for ${response.typeName}.`),
    'Response body envelope used when primitive or array payloads are combined with response headers.',
    [
      renderInterfaceMember(
        'body',
        getOperationResponseBodyValueTypeExpression(context, response),
        false,
        getResponseDocumentationDescription(response),
        response.schema != null
          ? resolveSchemaDeprecated(context.document, response.schema)
            ? 'This response body is deprecated.'
            : undefined
          : undefined
      ),
    ]
  );
};

const getAccessorWithContextInterfaceName = (interfaceName: string) =>
  `${interfaceName}_with_context`;

const renderAccessorInterface = (
  context: OpenApiContext,
  accessorGroup: AccessorGroupDefinition,
  withContext: boolean
) => {
  const members = accessorGroup.operations.map((operation) => {
    const argumentMode = getOperationArgumentMode(operation);
    const argumentTypeExpression = getOperationArgumentTypeExpression(
      context,
      operation
    );
    const optionsType = withContext
      ? 'AccessorOptionsWithContext<TAccessorContext>'
      : 'AccessorOptions';
    const optionsArgument = withContext
      ? `options: ${optionsType}`
      : `options?: ${optionsType} | undefined`;
    const responseTypeExpression = getOperationResponseTypeExpression(
      context,
      operation.response
    );
    const signature =
      argumentMode === 'none'
        ? `(${optionsArgument}) => Promise<${responseTypeExpression}>`
        : `(${[
            argumentMode === 'required'
              ? `args: ${argumentTypeExpression ?? fail(`Missing argument type for ${operation.namingSource}.`)}`
              : `args?: ${argumentTypeExpression ?? fail(`Missing argument type for ${operation.namingSource}.`)} | undefined`,
            optionsArgument,
          ].join(', ')}) => Promise<${responseTypeExpression}>`;
    const argumentDescription =
      argumentMode === 'none'
        ? undefined
        : getOperationArgumentDescription(context, operation);
    return [
      renderOperationDocumentationComment(
        operation.summary,
        operation.description,
        operation.deprecated ? 'This operation is deprecated.' : undefined,
        `${operation.method} ${operation.path}`,
        argumentDescription,
        withContext
          ? 'Additional accessor call options. The `context` value is passed to the sender for this accessor call.'
          : 'Additional accessor call options without per-call context.',
        getResponseDocumentationDescription(operation.response)
      ),
      `  readonly ${renderPropertyName(operation.memberName)}: ${signature};`,
    ].join('\n');
  });

  return renderInterfaceDefinition(
    withContext
      ? `${getAccessorWithContextInterfaceName(accessorGroup.interfaceName)}<TAccessorContext>`
      : accessorGroup.interfaceName,
    withContext
      ? `${accessorGroup.interfaceName} accessor definition that requires per-call context values.`
      : `${accessorGroup.interfaceName} accessor definition.`,
    members,
    withContext
      ? [
          {
            description: 'Per-call context value type passed to the sender.',
            name: 'TAccessorContext',
          },
        ]
      : undefined
  );
};

const renderAccessorInterfaces = (
  context: OpenApiContext,
  accessorGroup: AccessorGroupDefinition
) =>
  [
    renderAccessorInterface(context, accessorGroup, false),
    renderAccessorInterface(context, accessorGroup, true),
  ].join('\n\n');

const getOperationResponseHeadersConstName = (
  accessorGroup: AccessorGroupDefinition,
  operation: OperationDefinition
) =>
  `modestaResponseHeaders_${accessorGroup.interfaceName}_${operation.memberName}`;

const getOperationExcludedPropertiesConstName = (
  accessorGroup: AccessorGroupDefinition,
  operation: OperationDefinition
) =>
  `modestaExcludedProperties_${accessorGroup.interfaceName}_${operation.memberName}`;

const renderAccessorFactoryConstants = (
  context: OpenApiContext,
  accessorGroup: AccessorGroupDefinition
) => {
  const definitions: string[] = [];

  for (const operation of accessorGroup.operations) {
    if (operation.response.headers.length > 0) {
      definitions.push(
        `const ${getOperationResponseHeadersConstName(accessorGroup, operation)}: readonly AccessorResponseHeaderDescriptor[] = ${renderResponseHeaderDescriptorArray(
          context,
          operation.response.headers
        )};`
      );
    }

    if (
      operation.requestBody != null &&
      shouldUseRequestBodyEnvelope(context, operation) === false
    ) {
      const parameterPropertyNames = getOperationParameters(operation).map(
        (parameter) => parameter.propertyName
      );
      if (parameterPropertyNames.length > 0) {
        definitions.push(
          `const ${getOperationExcludedPropertiesConstName(accessorGroup, operation)} = ${renderLiteral(parameterPropertyNames)};`
        );
      }
    }
  }

  return definitions.join('\n');
};

const renderOperationResponseHeadersExpression = (
  accessorGroup: AccessorGroupDefinition,
  operation: OperationDefinition
) =>
  operation.response.headers.length === 0
    ? 'modestaEmptyResponseHeaders'
    : getOperationResponseHeadersConstName(accessorGroup, operation);

const renderAccessorFactory = (
  context: OpenApiContext,
  accessorGroup: AccessorGroupDefinition,
  schemaMetadata: SchemaMetadataRegistry
) => {
  const lines: string[] = [];
  const push = (value = '') => {
    lines.push(value);
  };
  const accessorWithContextInterfaceName = getAccessorWithContextInterfaceName(
    accessorGroup.interfaceName
  );
  const renderedConstants = renderAccessorFactoryConstants(
    context,
    accessorGroup
  );

  if (renderedConstants.length > 0) {
    push(renderedConstants);
    push();
  }

  push(
    renderTaggedDocumentationComment(
      `Creates a ${accessorGroup.interfaceName} accessor implementation.`,
      {
        params: [
          {
            description:
              'Sender implementation used to execute generated requests.',
            name: 'sender',
          },
        ],
        remarks:
          'When the sender requires per-call context values, the returned accessor methods require `options.context` for each invocation.',
        typeParams: [
          {
            description: 'Per-call context value type passed to the sender.',
            name: 'TAccessorContext',
          },
        ],
        returns: `${accessorGroup.interfaceName} accessor implementation bound to the provided sender.`,
      }
    )
  );
  push(
    `export function ${accessorGroup.factoryName}(sender: AccessorSender): ${accessorGroup.interfaceName};`
  );
  push(`export function ${accessorGroup.factoryName}<TAccessorContext>(`);
  push('  sender: AccessorSenderWithContext<TAccessorContext>');
  push(`): ${accessorWithContextInterfaceName}<TAccessorContext>;`);
  push(`export function ${accessorGroup.factoryName}<TAccessorContext>(`);
  push(
    '  sender: AccessorSender | AccessorSenderWithContext<TAccessorContext>'
  );
  push(
    `): ${accessorGroup.interfaceName} | ${accessorWithContextInterfaceName}<TAccessorContext> {`
  );
  push('  return {');

  for (const operation of accessorGroup.operations) {
    const argumentMode = getOperationArgumentMode(operation);
    const argumentToken =
      argumentMode === 'none'
        ? 'options'
        : argumentMode === 'required'
          ? 'args, options'
          : 'args, options';
    const responseTypeExpression = getOperationResponseTypeExpression(
      context,
      operation.response
    );
    push(
      `    ${renderPropertyName(operation.memberName)}: async (${argumentToken}) => modestaSend<${responseTypeExpression}>(sender, {`
    );
    push(
      `      operationName: ${renderLiteral(operation.descriptorOperationName)},`
    );
    push(`      method: ${renderLiteral(operation.method)},`);
    push(
      `      url: modestaBuildUrl(${[
        renderLiteral(operation.path),
        renderParameterArgumentObject(
          operation.pathParameters,
          argumentMode === 'optional'
        ),
        renderParameterArgumentObject(
          operation.queryParameters,
          argumentMode === 'optional'
        ),
      ].join(', ')}),`
    );
    push(
      `      headers: modestaBuildHeaders(${renderParameterArgumentObject(
        operation.headerParameters,
        argumentMode === 'optional'
      )}, ${operation.requestBody?.contentType != null ? renderLiteral(operation.requestBody.contentType) : 'undefined'}, ${operation.response.accept != null ? renderLiteral(operation.response.accept) : 'undefined'}),`
    );
    push(
      `      body: ${renderRequestBodyArgumentExpression(
        context,
        operation,
        accessorGroup,
        argumentMode === 'optional'
      )},`
    );
    const requestBodyMetadataName =
      schemaMetadata.getRequestBodyMetadataName(operation);
    if (requestBodyMetadataName != null) {
      push(`      requestBodyMetadata: ${requestBodyMetadataName},`);
    }
    push(
      `      responseContentType: ${operation.response.accept != null ? renderLiteral(operation.response.accept) : 'undefined'},`
    );
    const responseBodyMetadataName =
      schemaMetadata.getResponseBodyMetadataName(operation);
    if (responseBodyMetadataName != null) {
      push(`      responseBodyMetadata: ${responseBodyMetadataName},`);
    }
    push(
      `      responseHeaders: ${renderOperationResponseHeadersExpression(
        accessorGroup,
        operation
      )},`
    );
    push(
      `      wrapResponseBody: ${shouldUseResponseBodyEnvelope(
        context,
        operation.response
      )},`
    );
    push('    }, options),');
  }

  push(
    `  } as ${accessorGroup.interfaceName} | ${accessorWithContextInterfaceName}<TAccessorContext>;`
  );
  push('}');
  return lines.join('\n');
};

const renderNamedTypeDefinition = (
  context: OpenApiContext,
  typeName: string,
  schema: JsonRecord,
  description: string | undefined
) => {
  const deprecated = resolveSchemaDeprecated(context.document, schema);
  const referenceTypeExpression = getReferenceTypeExpression(context, schema);
  if (referenceTypeExpression != null) {
    return [
      renderDocumentationComment(
        description,
        deprecated ? 'This schema is deprecated.' : undefined
      ),
      `export type ${typeName} = ${referenceTypeExpression};`,
    ].join('\n');
  }

  const flattened =
    shouldPreserveAllOfReferences(schema) === false
      ? tryFlattenObjectSchema(context, schema, new Set<string>())
      : undefined;
  if (flattened != null) {
    const members = flattened.properties.map((property) =>
      renderInterfaceMember(
        property.propertyName,
        renderTypeExpression(context, property.schema, 1),
        property.required === false,
        property.description,
        property.deprecated ? 'This property is deprecated.' : undefined
      )
    );
    if (flattened.additionalPropertiesType != null) {
      members.push(
        `  readonly [key: string]: ${flattened.additionalPropertiesType};`
      );
    }
    return renderInterfaceDefinition(
      typeName,
      description,
      members,
      undefined,
      deprecated ? 'This schema is deprecated.' : undefined
    );
  }

  return [
    renderDocumentationComment(
      description,
      deprecated ? 'This schema is deprecated.' : undefined
    ),
    `export type ${typeName} = ${renderTypeExpression(context, schema, 0)};`,
  ].join('\n');
};

const renderInterfaceDefinition = (
  name: string,
  description: string | undefined,
  members: string[],
  typeParams:
    | { description: string | undefined; name: string }[]
    | undefined = undefined,
  deprecated: string | undefined = undefined
) => {
  const lines: string[] = [];
  lines.push(
    typeParams != null
      ? renderTaggedDocumentationComment(description, {
          deprecated,
          typeParams,
        })
      : renderDocumentationComment(description, deprecated)
  );
  lines.push(`export interface ${name} {`);
  if (members.length === 0) {
    lines.push('}');
    return lines.join('\n');
  }

  for (const member of members) {
    lines.push(member);
  }
  lines.push('}');
  return lines.join('\n');
};

const renderInterfaceMember = (
  name: string,
  type: string,
  optional: boolean,
  description: string | undefined,
  deprecated: string | undefined = undefined,
  readonly = true,
  remarks: string | undefined = undefined
) => {
  const lines: string[] = [];
  if (description != null || remarks != null || deprecated) {
    lines.push(
      indent(
        renderDocumentationCommentWithRemarks(description, remarks, deprecated),
        1
      )
    );
  }
  lines.push(
    `  ${readonly ? 'readonly ' : ''}${renderPropertyName(name)}${optional ? '?' : ''}: ${type};`
  );
  return lines.join('\n');
};

const renderDocumentationComment = (
  description: string | undefined,
  deprecated: string | undefined = undefined
) => {
  const lines = normalizeDocumentationLines(
    description,
    'Generated definition.'
  );
  if (lines.length === 0 && deprecated == null) {
    return '/** Generated definition. */';
  }

  if (lines.length === 1 && deprecated == null) {
    return `/** ${lines[0]} */`;
  }

  const commentLines = ['/**', ...lines.map((line) => ` * ${line}`)];
  if (deprecated != null) {
    appendTaggedDocumentationLines(commentLines, 'deprecated', '', deprecated);
  }
  commentLines.push(' */');
  return commentLines.join('\n');
};

const normalizeDocumentationLines = (
  description: string | undefined,
  fallback: string
) =>
  (description ?? fallback)
    .split(/\r?\n/u)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

const appendTaggedDocumentationLines = (
  lines: string[],
  tagName: 'deprecated' | 'param' | 'remarks' | 'returns' | 'typeParam',
  tagValue: string,
  description: string | undefined
) => {
  if (tagName === 'deprecated' && description == null) {
    lines.push(' * @deprecated');
    return;
  }

  const normalizedLines = normalizeDocumentationLines(description, tagValue);
  if (normalizedLines.length === 0) {
    return;
  }

  const tagPrefix =
    tagValue.length > 0 ? ` * @${tagName} ${tagValue}` : ` * @${tagName}`;
  lines.push(`${tagPrefix} ${normalizedLines[0]}`);
  for (const line of normalizedLines.slice(1)) {
    lines.push(` * ${line}`);
  }
};

const renderTaggedDocumentationComment = (
  description: string | undefined,
  options: {
    deprecated?: string | undefined;
    params?: { description: string | undefined; name: string }[] | undefined;
    remarks?: string | undefined;
    returns?: string | undefined;
    typeParams?:
      | { description: string | undefined; name: string }[]
      | undefined;
  }
) => {
  const lines = ['/**'];
  lines.push(
    ...normalizeDocumentationLines(description, 'Generated definition.').map(
      (line) => ` * ${line}`
    )
  );
  if (options.deprecated != null) {
    appendTaggedDocumentationLines(lines, 'deprecated', '', options.deprecated);
  }

  for (const typeParam of options.typeParams ?? []) {
    appendTaggedDocumentationLines(
      lines,
      'typeParam',
      typeParam.name,
      typeParam.description
    );
  }
  for (const parameter of options.params ?? []) {
    appendTaggedDocumentationLines(
      lines,
      'param',
      parameter.name,
      parameter.description
    );
  }
  if (options.returns != null) {
    appendTaggedDocumentationLines(lines, 'returns', '', options.returns);
  }
  if (options.remarks != null) {
    appendTaggedDocumentationLines(lines, 'remarks', '', options.remarks);
  }

  lines.push(' */');
  return lines.join('\n');
};

const renderParameterArgumentObject = (
  parameters: ParameterDefinition[],
  optionalArguments: boolean
) => {
  if (parameters.length === 0) {
    return '{}';
  }

  return [
    '{',
    ...parameters.map(
      (parameter) =>
        `  ${renderPropertyName(parameter.name)}: ${optionalArguments ? `args?.[${renderLiteral(parameter.propertyName)}]` : `args[${renderLiteral(parameter.propertyName)}]`},`
    ),
    '}',
  ].join('\n');
};

const renderResponseHeaderDescriptorArray = (
  context: OpenApiContext,
  headers: readonly ResponseHeaderDefinition[]
) => {
  if (headers.length === 0) {
    return '[]';
  }

  return [
    '[',
    ...headers.map((header) => {
      const descriptor = getResponseHeaderValueDescriptor(
        context,
        header.schema
      );
      const properties = [
        `name: ${renderLiteral(header.name)}`,
        `propertyName: ${renderLiteral(header.propertyName)}`,
        `valueType: ${renderLiteral(descriptor.valueType)}`,
      ];
      if (descriptor.itemValueType != null) {
        properties.push(
          `itemValueType: ${renderLiteral(descriptor.itemValueType)}`
        );
      }
      return `  { ${properties.join(', ')} },`;
    }),
    ']',
  ].join('\n');
};

const renderOperationDocumentationComment = (
  summary: string | undefined,
  remarks: string | undefined,
  deprecated: string | undefined,
  fallback: string,
  argumentDescription: string | undefined,
  optionsDescription: string,
  returnDescription: string
) => {
  const normalizedSummary = summary?.trim();
  const normalizedRemarks = remarks?.trim();
  const descriptionLines = normalizeDocumentationLines(
    normalizedSummary != null && normalizedSummary.length > 0
      ? summary
      : remarks,
    fallback
  );

  if (descriptionLines.length === 0) {
    return renderDocumentationComment(fallback);
  }

  const lines = ['/**', ...descriptionLines.map((line) => ` * ${line}`)];
  if (deprecated != null) {
    appendTaggedDocumentationLines(lines, 'deprecated', '', deprecated);
  }
  const hasDistinctRemarks =
    normalizedSummary != null &&
    normalizedSummary.length > 0 &&
    normalizedRemarks != null &&
    normalizedRemarks.length > 0 &&
    normalizedRemarks !== normalizedSummary;

  if (hasDistinctRemarks) {
    lines.push(' *');
    appendTaggedDocumentationLines(lines, 'remarks', '', remarks);
  }

  if (argumentDescription != null) {
    appendTaggedDocumentationLines(lines, 'param', 'args', argumentDescription);
  }
  appendTaggedDocumentationLines(lines, 'param', 'options', optionsDescription);
  appendTaggedDocumentationLines(lines, 'returns', '', returnDescription);
  lines.push(' */');

  return lines.join('\n');
};

const renderDocumentationCommentWithRemarks = (
  description: string | undefined,
  remarks: string | undefined,
  deprecated: string | undefined = undefined
) => {
  if (remarks == null) {
    return renderDocumentationComment(description, deprecated);
  }

  const lines = ['/**'];
  if (description != null) {
    lines.push(
      ...normalizeDocumentationLines(description, '').map(
        (line) => ` * ${line}`
      )
    );
  }
  if (deprecated != null) {
    appendTaggedDocumentationLines(lines, 'deprecated', '', deprecated);
  }
  appendTaggedDocumentationLines(lines, 'remarks', '', remarks);
  lines.push(' */');
  return lines.join('\n');
};

const getResponseDocumentationDescription = (response: ResponseDefinition) =>
  response.description ?? `Response type for HTTP ${response.statusCode}.`;

const getOperationArgumentMode = (operation: OperationDefinition) => {
  const hasArguments =
    getOperationParameters(operation).length > 0 ||
    operation.requestBody != null;
  if (hasArguments === false) {
    return 'none' as const;
  }

  const requiresArguments =
    getOperationParameters(operation).some((parameter) => parameter.required) ||
    (operation.requestBody?.required ?? false);
  return requiresArguments ? ('required' as const) : ('optional' as const);
};

const getOperationArgumentTypeExpression = (
  context: OpenApiContext,
  operation: OperationDefinition
) => {
  const parameterCount = getOperationParameters(operation).length;
  if (operation.requestBody == null) {
    return parameterCount > 0 ? operation.argumentsTypeName : undefined;
  }

  const requestBodyTypeExpression = getOperationRequestArgumentTypeExpression(
    context,
    operation
  );
  if (parameterCount === 0) {
    return requestBodyTypeExpression;
  }

  return `${requestBodyTypeExpression} & ${operation.argumentsTypeName}`;
};

const getOperationArgumentDescription = (
  context: OpenApiContext,
  operation: OperationDefinition
) => {
  const hasParameters = getOperationParameters(operation).length > 0;
  const baseDescription =
    getOperationArgumentMode(operation) === 'required'
      ? `Arguments for ${operation.method} ${operation.path}.`
      : `Optional arguments for ${operation.method} ${operation.path}.`;
  if (operation.requestBody == null) {
    return baseDescription;
  }

  const lines = [baseDescription];
  const wrappedRequestBody = shouldUseRequestBodyEnvelope(context, operation);
  lines.push(
    hasParameters
      ? wrappedRequestBody
        ? 'Request body payload is passed via args.body, and flattened path/query/header parameters are passed at the top level.'
        : 'Request body fields and flattened path/query/header parameters are passed at the top level.'
      : wrappedRequestBody
        ? 'Request body payload is passed via args.body.'
        : 'Request body payload is passed directly as args.'
  );
  if (operation.requestBody.parameterDescription != null) {
    lines.push(`Request body: ${operation.requestBody.parameterDescription}`);
  }
  return lines.join('\n');
};

const isSimpleOperationTypeExpression = (typeExpression: string) => {
  return (
    typeExpression.includes('\n') === false &&
    typeExpression.includes('{') === false &&
    typeExpression.includes('}') === false
  );
};

const getOperationSchemaTypeExpression = (
  context: OpenApiContext,
  schema: JsonRecord,
  typeName: string
) => {
  const typeExpression = renderTypeExpression(context, schema, 0);
  return isSimpleOperationTypeExpression(typeExpression)
    ? typeExpression
    : typeName;
};

const shouldRenderOperationSchemaDefinition = (
  context: OpenApiContext,
  schema: JsonRecord
) => {
  return (
    isSimpleOperationTypeExpression(
      renderTypeExpression(context, schema, 0)
    ) === false
  );
};

const shouldUseRequestBodyEnvelope = (
  context: OpenApiContext,
  operation: OperationDefinition
) => {
  return (
    operation.requestBody != null &&
    getOperationParameters(operation).length > 0 &&
    isSchemaObjectLike(context.document, operation.requestBody.schema) === false
  );
};

const shouldUseResponseBodyEnvelope = (
  context: OpenApiContext,
  response: ResponseDefinition
) => {
  return (
    response.schema != null &&
    response.headers.length > 0 &&
    isSchemaObjectLike(context.document, response.schema) === false
  );
};

const getOperationRequestBodyTypeExpression = (
  context: OpenApiContext,
  requestBody: RequestBodyDefinition
) => {
  return getOperationSchemaTypeExpression(
    context,
    requestBody.schema,
    requestBody.typeName
  );
};

const getOperationRequestArgumentTypeExpression = (
  context: OpenApiContext,
  operation: OperationDefinition
) => {
  const requestBody =
    operation.requestBody ??
    fail(`Missing request body for ${operation.namingSource}.`);
  return shouldUseRequestBodyEnvelope(context, operation)
    ? (requestBody.envelopeTypeName ??
        fail(`Missing request envelope type for ${requestBody.typeName}.`))
    : getOperationRequestBodyTypeExpression(context, requestBody);
};

const getOperationResponseBodyValueTypeExpression = (
  context: OpenApiContext,
  response: ResponseDefinition
) => {
  return response.schema == null
    ? 'void'
    : getOperationSchemaTypeExpression(
        context,
        response.schema,
        response.typeName
      );
};

const getOperationResponseBodyTypeExpression = (
  context: OpenApiContext,
  response: ResponseDefinition
) => {
  if (response.schema == null) {
    return undefined;
  }

  return shouldUseResponseBodyEnvelope(context, response)
    ? (response.bodyEnvelopeTypeName ??
        fail(`Missing response body envelope type for ${response.typeName}.`))
    : getOperationResponseBodyValueTypeExpression(context, response);
};

const getOperationResponseHeadersTypeExpression = (
  response: ResponseDefinition
) => {
  return response.headers.length > 0
    ? (response.headersTypeName ??
        fail(`Missing response headers type for ${response.typeName}.`))
    : undefined;
};

const getOperationResponseTypeExpression = (
  context: OpenApiContext,
  response: ResponseDefinition
) => {
  const responseBodyTypeExpression = getOperationResponseBodyTypeExpression(
    context,
    response
  );
  const responseHeadersTypeExpression =
    getOperationResponseHeadersTypeExpression(response);

  if (
    responseBodyTypeExpression == null &&
    responseHeadersTypeExpression == null
  ) {
    return 'void';
  }
  if (responseBodyTypeExpression == null) {
    return responseHeadersTypeExpression!;
  }
  if (responseHeadersTypeExpression == null) {
    return responseBodyTypeExpression;
  }
  return `${responseBodyTypeExpression} & ${responseHeadersTypeExpression}`;
};

const getReferenceTypeExpression = (
  context: OpenApiContext,
  schema: JsonRecord
) => {
  const directReference = getDirectReference(schema);
  if (directReference != null && isReferenceWrapperSchema(schema)) {
    return resolveReferenceTypeName(context, directReference);
  }

  const allOfReference = getSingleReferenceFromAllOf(schema);
  if (allOfReference != null && isAllOfReferenceWrapperSchema(schema)) {
    return resolveReferenceTypeName(context, allOfReference);
  }

  return undefined;
};

const shouldPreserveAllOfReferences = (schema: JsonRecord) => {
  const allOf = asArray(schema.allOf);
  if (allOf == null) {
    return false;
  }

  return allOf.some((entry) => {
    const entryRecord = asRecord(entry);
    return (
      entryRecord != null &&
      (isReferenceWrapperSchema(entryRecord) ||
        isAllOfReferenceWrapperSchema(entryRecord))
    );
  });
};

const getDirectAllOfObjectShape = (
  schema: JsonRecord
): JsonRecord | undefined => {
  const properties = getRecord(schema, 'properties');
  if (properties == null && schema.additionalProperties == null) {
    return undefined;
  }

  const directShape: JsonRecord = {
    additionalProperties: schema.additionalProperties,
    properties,
  };
  const required = asArray(schema.required);
  if (required != null) {
    directShape.required = required;
  }
  if (getString(schema, 'type') === 'object') {
    directShape.type = 'object';
  }

  return directShape;
};

const renderAllOfTypeExpression = (
  context: OpenApiContext,
  schema: JsonRecord,
  indentLevel: number
) => {
  const allOf = asArray(schema.allOf);
  if (allOf == null) {
    throw new Error('Could not resolve allOf schema entries.');
  }

  const expressions = allOf.map((entry) => {
    const entryRecord = asRecord(entry);
    if (entryRecord == null) {
      throw new Error('Could not resolve allOf schema entry.');
    }
    return renderTypeExpression(context, entryRecord, indentLevel);
  });
  const directObjectShape = getDirectAllOfObjectShape(schema);
  if (directObjectShape != null) {
    expressions.push(
      renderTypeExpression(context, directObjectShape, indentLevel)
    );
  }

  return expressions.join(' & ');
};

const renderTypeExpression = (
  context: OpenApiContext,
  schema: JsonRecord,
  indentLevel: number
): string => {
  if (hasUnsupportedComposition(schema)) {
    throw new Error(
      'Unsupported schema composition detected. oneOf/anyOf/discriminator is not supported.'
    );
  }

  const nullable = getBoolean(schema, 'nullable') ?? false;
  let coreType: string;
  const referenceTypeExpression = getReferenceTypeExpression(context, schema);

  if (referenceTypeExpression != null) {
    coreType = referenceTypeExpression;
  } else if (asArray(schema.allOf) != null) {
    if (shouldPreserveAllOfReferences(schema)) {
      coreType = renderAllOfTypeExpression(context, schema, indentLevel);
    } else {
      const flattened = tryFlattenObjectSchema(
        context,
        schema,
        new Set<string>()
      );
      if (flattened != null) {
        coreType = renderInlineObjectType(flattened, indentLevel);
      } else {
        coreType = renderAllOfTypeExpression(context, schema, indentLevel);
      }
    }
  } else if (asArray(schema.enum) != null) {
    coreType = renderEnumType(asArray(schema.enum)!);
  } else {
    const typeName = getString(schema, 'type');
    switch (typeName) {
      case 'string':
        coreType = 'string';
        break;
      case 'number':
      case 'integer':
        coreType = 'number';
        break;
      case 'boolean':
        coreType = 'boolean';
        break;
      case 'array':
        coreType = `ReadonlyArray<${renderTypeExpression(
          context,
          getRequiredRecord(schema, 'items', 'array items'),
          indentLevel
        )}>`;
        break;
      case 'object':
      default:
        if (isObjectSchema(schema)) {
          const flattened = tryFlattenObjectSchema(
            context,
            schema,
            new Set<string>()
          );
          if (flattened == null) {
            throw new Error('Could not flatten object schema.');
          }
          coreType = renderInlineObjectType(flattened, indentLevel);
          break;
        }

        if (typeName == null) {
          coreType = 'unknown';
          break;
        }

        throw new Error(`Unsupported schema type: ${typeName}`);
    }
  }

  return nullable ? `${coreType} | null` : coreType;
};

const renderEnumType = (values: unknown[]) => {
  const normalized = values.map((value) => renderLiteral(value));
  return normalized.join(' | ');
};

const renderInlineObjectType = (
  flattened: FlattenedObjectSchema,
  indentLevel: number
) => {
  const members: string[] = [];
  for (const property of flattened.properties) {
    if (property.description != null) {
      members.push(
        indent(
          renderDocumentationComment(
            property.description,
            property.deprecated ? 'This property is deprecated.' : undefined
          ),
          1
        )
      );
    }
    members.push(
      `  ${renderPropertyName(property.propertyName)}${property.required ? '' : '?'}: ${property.typeExpression};`
    );
  }
  if (flattened.additionalPropertiesType != null) {
    members.push(`  [key: string]: ${flattened.additionalPropertiesType};`);
  }

  if (members.length === 0) {
    return 'Record<string, never>';
  }

  return `{\n${indent(members.join('\n'), indentLevel)}\n${'  '.repeat(indentLevel)}}`;
};

interface FlattenedProperty {
  description: string | undefined;
  deprecated: boolean;
  propertyName: string;
  required: boolean;
  schema: JsonRecord;
  typeExpression: string;
}

interface FlattenedObjectSchema {
  additionalPropertiesType: string | undefined;
  properties: FlattenedProperty[];
}

const tryFlattenObjectSchema = (
  context: OpenApiContext,
  schema: JsonRecord,
  visitedReferences: Set<string>
): FlattenedObjectSchema | undefined => {
  const expanded = expandObjectShape(context, schema, visitedReferences);
  if (expanded == null) {
    return undefined;
  }

  return {
    additionalPropertiesType:
      expanded.additionalPropertiesSchema != null
        ? renderTypeExpression(context, expanded.additionalPropertiesSchema, 1)
        : undefined,
    properties: expanded.properties
      .sort((left, right) => left.name.localeCompare(right.name))
      .map((property) => ({
        description: property.description,
        deprecated: property.deprecated,
        propertyName: property.name,
        required: property.required,
        schema: property.schema,
        typeExpression: renderTypeExpression(context, property.schema, 1),
      })),
  };
};

interface ExpandedProperty {
  description: string | undefined;
  deprecated: boolean;
  name: string;
  required: boolean;
  schema: JsonRecord;
}

interface ExpandedObjectShape {
  additionalPropertiesSchema: JsonRecord | undefined;
  properties: ExpandedProperty[];
}

const expandObjectShape = (
  context: OpenApiContext,
  schema: JsonRecord,
  visitedReferences: Set<string>
): ExpandedObjectShape | undefined => {
  if (hasUnsupportedComposition(schema)) {
    throw new Error(
      'Unsupported schema composition detected. oneOf/anyOf/discriminator is not supported.'
    );
  }

  if (isPureReference(schema)) {
    const reference = getRequiredString(schema, '$ref', '$ref');
    if (visitedReferences.has(reference)) {
      throw new Error(
        `Circular object schema reference is not supported in flattening: ${reference}`
      );
    }
    visitedReferences.add(reference);
    const resolved = resolveReferenceObject(context.document, schema);
    const expanded = expandObjectShape(
      context,
      resolved ?? schema,
      visitedReferences
    );
    visitedReferences.delete(reference);
    return expanded;
  }

  const allOf = asArray(schema.allOf);
  if (allOf != null) {
    const mergedProperties = new Map<string, ExpandedProperty>();
    let additionalPropertiesSchema: JsonRecord | undefined;
    for (const entry of allOf) {
      const expanded = expandObjectShape(
        context,
        resolveSchemaObject(context.document, asRecord(entry)),
        visitedReferences
      );
      if (expanded == null) {
        return undefined;
      }

      for (const property of expanded.properties) {
        mergedProperties.set(property.name, property);
      }

      if (expanded.additionalPropertiesSchema != null) {
        additionalPropertiesSchema = expanded.additionalPropertiesSchema;
      }
    }

    const direct = expandDirectObjectShape(context, schema);
    if (direct != null) {
      for (const property of direct.properties) {
        mergedProperties.set(property.name, property);
      }
      if (direct.additionalPropertiesSchema != null) {
        additionalPropertiesSchema = direct.additionalPropertiesSchema;
      }
    }

    return {
      additionalPropertiesSchema,
      properties: Array.from(mergedProperties.values()),
    };
  }

  return expandDirectObjectShape(context, schema);
};

const expandDirectObjectShape = (
  context: OpenApiContext,
  schema: JsonRecord
): ExpandedObjectShape | undefined => {
  if (isObjectSchema(schema) === false) {
    return undefined;
  }

  const properties = getRecord(schema, 'properties') ?? {};
  const requiredNames = new Set(
    (asArray(schema.required) ?? [])
      .map((name) => (typeof name === 'string' ? name : undefined))
      .filter((name): name is string => name != null)
  );

  const expandedProperties = Object.keys(properties).map((propertyName) => {
    const propertySchema = asRecord(properties[propertyName]);
    if (propertySchema == null) {
      throw new Error(`Could not resolve property schema: ${propertyName}`);
    }
    const resolvedPropertySchema = resolveSchemaObject(
      context.document,
      propertySchema
    );
    return {
      description:
        getString(propertySchema, 'description') ??
        getString(resolvedPropertySchema, 'description'),
      deprecated:
        getBoolean(propertySchema, 'deprecated') ??
        getBoolean(resolvedPropertySchema, 'deprecated') ??
        false,
      name: propertyName,
      required: requiredNames.has(propertyName),
      schema: propertySchema,
    } satisfies ExpandedProperty;
  });

  const rawAdditionalProperties = schema.additionalProperties;
  let additionalPropertiesSchema: JsonRecord | undefined;
  if (rawAdditionalProperties === true) {
    additionalPropertiesSchema = {};
  } else {
    const additionalPropertiesRecord = asRecord(rawAdditionalProperties);
    if (additionalPropertiesRecord != null) {
      additionalPropertiesSchema = additionalPropertiesRecord;
    }
  }

  return {
    additionalPropertiesSchema,
    properties: expandedProperties,
  };
};

const isObjectSchema = (schema: JsonRecord) => {
  if (getString(schema, 'type') === 'object') {
    return true;
  }
  if (getRecord(schema, 'properties') != null) {
    return true;
  }
  if (schema.additionalProperties != null) {
    return true;
  }
  if (asArray(schema.allOf) != null) {
    return true;
  }
  return false;
};

const hasUnsupportedComposition = (schema: JsonRecord) => {
  return (
    asArray(schema.oneOf) != null ||
    asArray(schema.anyOf) != null ||
    getRecord(schema, 'discriminator') != null
  );
};

const renderRequestBodyArgumentExpression = (
  context: OpenApiContext,
  operation: OperationDefinition,
  accessorGroup: AccessorGroupDefinition,
  optionalArguments: boolean
) => {
  if (operation.requestBody == null) {
    return 'undefined';
  }

  if (shouldUseRequestBodyEnvelope(context, operation)) {
    return optionalArguments ? 'args?.body' : 'args.body';
  }

  const parameterPropertyNames = getOperationParameters(operation).map(
    (parameter) => parameter.propertyName
  );
  if (parameterPropertyNames.length === 0) {
    return 'args';
  }

  return `modestaExcludeProperties(args, ${getOperationExcludedPropertiesConstName(
    accessorGroup,
    operation
  )})`;
};

const getResponseHeaderValueDescriptor = (
  context: OpenApiContext,
  schema: JsonRecord
): {
  itemValueType: 'string' | 'number' | 'boolean' | 'unknown' | undefined;
  valueType: 'string' | 'number' | 'boolean' | 'array' | 'unknown';
} => {
  const directReference = getDirectReference(schema);
  if (directReference != null) {
    const resolved = resolveReferenceObject(context.document, schema);
    return resolved != null
      ? getResponseHeaderValueDescriptor(context, resolved)
      : { itemValueType: undefined, valueType: 'unknown' };
  }

  const allOfReference = getSingleReferenceFromAllOf(schema);
  if (allOfReference != null) {
    const resolved = resolveReferenceObject(context.document, {
      $ref: allOfReference,
    });
    return resolved != null
      ? getResponseHeaderValueDescriptor(context, resolved)
      : { itemValueType: undefined, valueType: 'unknown' };
  }

  switch (getString(schema, 'type')) {
    case 'string':
      return { itemValueType: undefined, valueType: 'string' };
    case 'number':
    case 'integer':
      return { itemValueType: undefined, valueType: 'number' };
    case 'boolean':
      return { itemValueType: undefined, valueType: 'boolean' };
    case 'array': {
      const items = getRecord(schema, 'items');
      if (items == null) {
        return { itemValueType: 'unknown', valueType: 'array' };
      }
      const itemDescriptor = getResponseHeaderValueDescriptor(context, items);
      return {
        itemValueType:
          itemDescriptor.valueType === 'array'
            ? 'unknown'
            : itemDescriptor.valueType,
        valueType: 'array',
      };
    }
    default:
      return { itemValueType: undefined, valueType: 'unknown' };
  }
};

const getOperationParameters = (operation: OperationDefinition) => {
  return [
    ...operation.pathParameters,
    ...operation.queryParameters,
    ...operation.headerParameters,
  ];
};

const resolveReferenceTypeName = (
  context: OpenApiContext,
  reference: string
) => {
  const match = /^#\/components\/schemas\/(.+)$/u.exec(reference);
  if (match == null) {
    const resolved = resolveReferenceObject(context.document, {
      $ref: reference,
    });
    return renderTypeExpression(context, resolved ?? {}, 0);
  }

  const mapped = context.naming.schemaTypeNames.get(match[1]);
  if (mapped == null) {
    throw new Error(`Unknown schema reference: ${reference}`);
  }
  return mapped;
};
